sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tHZwBnjtka5cBoswDZZ
    access-key-secret: XswUM292cI3w95SEB4hIymIlxDLuG0
    bucket-name: sky-ouyang

